import type { CommandDefinition } from './types';

export const commandDefinitions: CommandDefinition[] = [
  {
    name: '/listen',
    label: 'Listen',
    description: 'Default routed pass through primary, secondary, and corrective ears.',
    skillsCalled: ['akouo-router'],
    executionOrder: ['Run router', 'Run primary mode', 'Run secondary mode', 'Run corrective mode'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/full-ear',
    label: 'Full ear',
    description: 'Broad multimodal scan for deep listening across signal, object, music/aesthetics, body, and mediation.',
    skillsCalled: [
      'akouo-router',
      'signal-inspection-listening',
      'acoulogical-object-listening',
      'musical-aesthetic-listening',
      'embodied-affective-listening',
      'transductive-media-listening',
      'material-event-listening',
    ],
    executionOrder: ['Route context', 'Inspect signal', 'Describe auditum', 'Map musical/aesthetic organization', 'Map affect', 'Map mediation', 'Map material event when relevant'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/study',
    label: 'Study',
    description: 'Research-oriented command for sonic methods, critique, ecology, fiction, and references.',
    skillsCalled: [
      'acoulogical-object-listening',
      'musical-aesthetic-listening',
      'critical-political-listening',
      'ecological-posthuman-listening',
      'symbolic-fictional-listening',
      'reference-layer',
    ],
    executionOrder: ['Ground perceptually', 'Map musical/aesthetic organization if relevant', 'Critique mediations', 'Choose ecological or fictional route', 'Map references'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/tech',
    label: 'Tech',
    description: 'Technical inspection of file, waveform, spectrogram, metadata, and media chain.',
    skillsCalled: ['signal-inspection-listening', 'transductive-media-listening'],
    executionOrder: ['Inspect signal', 'Map mediation if relevant'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/reference',
    label: 'Reference',
    description: 'Conceptual map of methods, authors, traditions, cautions, and adjacent modes.',
    skillsCalled: ['reference-layer'],
    executionOrder: ['Identify concepts', 'Map traditions', 'Name cautions', 'Suggest routes'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/litany',
    label: 'Litany',
    description: 'Audits sonic or audiovisual claims for simplistic sound-versus-vision binaries.',
    skillsCalled: ['critical-political-listening', 'transductive-media-listening', 'audiovisual-scenic-listening', 'acoulogical-object-listening'],
    executionOrder: ['Audit critique', 'Map mediation', 'Map audiovisual scene if relevant', 'Reground in object if needed'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/fiction',
    label: 'Fiction',
    description: 'Declared speculative sonic worldbuilding with affective and critical corrections.',
    skillsCalled: [
      'symbolic-fictional-listening',
      'embodied-affective-listening',
      'ecological-posthuman-listening',
      'critical-political-listening',
    ],
    executionOrder: ['Declare fiction frame', 'Map affect', 'Map nonhuman world if relevant', 'Run critique if needed'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/forensic',
    label: 'Forensic',
    description: 'Strict evidentiary pass for testimony, archives, damage, and recordings with harm risk.',
    skillsCalled: ['signal-inspection-listening', 'forensic-archival-listening', 'critical-political-listening'],
    executionOrder: ['Inspect signal', 'Separate evidence levels', 'Name political and archival stakes'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/transduce',
    label: 'Transduce',
    description: 'Maps conversion across sensors, codecs, models, sonification, platforms, and interfaces.',
    skillsCalled: ['transductive-media-listening', 'signal-inspection-listening', 'voice-speech-listening', 'accessibility-normative-listening', 'critical-political-listening'],
    executionOrder: ['Map conversion', 'Inspect artifacts', 'Analyze voice mediation if present', 'Audit access path if present', 'Critique institutional stakes if present'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/one-sound-many-ears',
    label: 'One sound many ears',
    description: 'Comparative flagship command that runs one object through every public listening ear.',
    skillsCalled: [
      'signal-inspection-listening',
      'acoulogical-object-listening',
      'embodied-affective-listening',
      'transductive-media-listening',
      'forensic-archival-listening',
      'ecological-posthuman-listening',
      'critical-political-listening',
      'musical-aesthetic-listening',
      'symbolic-fictional-listening',
      'audiovisual-scenic-listening',
      'voice-speech-listening',
      'accessibility-normative-listening',
      'material-event-listening',
    ],
    executionOrder: ['Run all listening modes', 'Compare contradictions', 'Name tensions', 'Recommend next ear'],
    outputSchema: 'schemas/comparative-listening-output.schema.json',
  },
  {
    name: '/voice',
    label: 'Voice',
    description: 'Voice and speech pass for spoken sound, transcripts, ASR, TTS, voice agents, identity caution, and consent.',
    skillsCalled: ['voice-speech-listening', 'transductive-media-listening', 'accessibility-normative-listening', 'critical-political-listening'],
    executionOrder: ['Separate voice from transcript', 'Map speech/voice mediation', 'Audit access path', 'Apply political/consent corrective when needed'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/audiovision',
    label: 'Audiovision',
    description: 'Sound-image-scene pass for video, film, games, subtitles, synchronization, UI sound, and audiovisual phrasing.',
    skillsCalled: ['audiovisual-scenic-listening', 'acoulogical-object-listening', 'voice-speech-listening', 'critical-political-listening'],
    executionOrder: ['Map sound-image relation', 'Ground the sound object', 'Analyze voice/text if relevant', 'Audit audiovisual assumptions'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/access',
    label: 'Access',
    description: 'Accessibility and hearing-norm audit for captions, transcripts, haptics, alerts, voice agents, and sonic interfaces.',
    skillsCalled: ['accessibility-normative-listening', 'voice-speech-listening', 'embodied-affective-listening', 'critical-political-listening'],
    executionOrder: ['Identify implied listener', 'Audit speech/caption path when relevant', 'Check body and attention load', 'Name access and power stakes'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/field',
    label: 'Field',
    description: 'Field recording route for place, habitat, soundscape/acoustemology/aurality distinctions, sensors, and fieldwork ethics.',
    skillsCalled: ['ecological-posthuman-listening', 'transductive-media-listening', 'critical-political-listening', 'material-event-listening'],
    executionOrder: ['Map ecological layers', 'Map capture and elsewhere-listening mediation', 'Audit fieldwork ethics', 'Map material event and scale'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/method',
    label: 'Method',
    description: 'Sonic methodology route for research design, listening practice, references, access, and agent handoff.',
    skillsCalled: ['akouo-router', 'acoulogical-object-listening', 'critical-political-listening', 'accessibility-normative-listening', 'reference-layer'],
    executionOrder: ['Route the research situation', 'Ground perceptually', 'Audit method and access', 'Map references and next workflow'],
    outputSchema: 'schemas/command-output.schema.json',
  },
  {
    name: '/route',
    label: 'Route',
    description: 'Router-only handoff plan for other agents and frameworks, including evidence limits and mode chain.',
    skillsCalled: ['akouo-router'],
    executionOrder: ['Identify evidence', 'Score listening frames', 'Return mode chain and forbidden assumptions'],
    outputSchema: 'schemas/router-output.schema.json',
  },
];
